apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-default-sa-argo-workflows-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-server
subjects:
- kind: ServiceAccount
  name: argo-workflow-default-sa
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-default-sa-argo-workflows-server-cluster-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-server-cluster-template
subjects:
- kind: ServiceAccount
  name: argo-workflow-default-sa
  namespace: argo
