apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: app
  name: workflow-template
spec:
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
  - name: main
    dag:
      tasks:
      - name: inner-A
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: hello world
      - name: inner-B
        dependencies: [inner-A]
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: hello again
  - name: main-on-monday
    dag:
      tasks:
      - name: inner-A
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: hello monday
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  namespace: app
  name: cron-workflow-on-monday
spec:
  schedule: "0 6 * * 1"
  timezone: "Asia/Tokyo"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Allow"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  suspend: false
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: run
              templateRef:
                name: workflow-template
                template: main-on-monday
